# Generated by Django 4.2.2 on 2023-06-13 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created"]},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="date",
        ),
        migrations.AddField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="body",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(default="johndoe@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default="John Doe", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created"], name="articles_co_created_2fb7bd_idx"
            ),
        ),
    ]
